### ISSUE TITLE
Falta una imagen

### ISSUE THREAD

**Issue by JuanCarlosOltra** [guilleatm/github-light#1]
Falta una imagen en github-light/assets/images
No existe "gh-pages-config.png"

**Comment by guilleatm** [comment]
@JuanCarlosOltra toda la razón, gracias por comentarlo y por abrir un issue.

El problema está aquí:
https://github.com/guilleatm/github-light/blob/ec998bc1257c3c86c82897d00f0f725543c1e2a5/github.md?plain=1#L74

*podeis especificar exactamente dónde habeis encontrado el fallo utilizando los permalinks

![Screenshot_20241014_110736](https://github.com/user-attachments/assets/fe74d5d5-5260-47df-b425-5227daa500d4)

*de igual forma podeis adjuntar imágenes

**Comment by guilleatm** [comment]
He creado una rama para solucionar el problema, es este caso es algo sencillo y solo requiere de un commit (817af148e601b19990286e07c668b69b896ce43d)

**Comment by guilleatm** [comment]
Con los cambios realizados, podemos hacer un [pull request](https://guilleatm.github.io/github-light/concepts.html#pull-request) para introducirlos en la rama principal.

He creado y aprobado [este pull request](https://github.com/guilleatm/github-light/pull/2).
